# cat time.sh
#!/bin/bash
BASE_PATH=$(cd `dirname $0`; pwd)
CURRENT_PATH="`pwd -P`"
#工程根目录
PROJECT_ROOT_PATH=${1-$CURRENT_PATH};

echo "工程根目录-->"$PROJECT_ROOT_PATH

echo "创建local.properties到工程根目录..."
echo "## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=$ANDROID_SDK">>local.properties

echo "执行gradlew assembleDebug..."
cd $PROJECT_ROOT_PATH
./gradlew assembleDebug